### ISSUE TITLE
Cannot send message to UI through WebSocket on examlpe code

### ISSUE THREAD

**Issue by bihjuchiu** [BitTigerInst/BitTiger-CS504-FAQ#40]
Try to run running-location-updater project from CS504-week3-4-for-students.zip (Downloaded from 第四周实战课):

Steps to reproduce:

Start Docker environment
> docker-compose up

Start the server:
> sh ./start-location-updater.sh

Enter UI site:
http://localhost:9007/

Click "Subscribe to Location Updates"
Then click "Send Test Message"

See "sendMessage triggered" displayed, but didn't see the test message displayed on UI.

On server side:
See the following error message, but can't figure out what's wrong w/ the code:
```
2017-05-24 02:08:16.876 ERROR 4747 --- [nboundChannel-3] .WebSocketAnnotationMethodMessageHandler : Unhandled exception

org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@3ddd4450; line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@3ddd4450; line: 1, column: 1]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:223) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:175) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:67) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.annotation.support.PayloadArgumentResolver.resolveArgument(PayloadArgumentResolver.java:115) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:77) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:129) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:102) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:462) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:482) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:86) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:423) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:361) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:135) [spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: [B@3ddd4450; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2851) ~[jackson-databind-2.6.3.jar!/:2.6.3]
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:210) ~[spring-messaging-4.2.2.RELEASE.jar!/:4.2.2.RELEASE]
	... 15 common frames omitted

```

**Comment by zhuzzz** [comment]
Same problem here... 
Did you figure out the reason?

**Comment by bihjuchiu** [comment]
Not yet...

**Comment by hackjutsu** [comment]
我看看哈……

**Comment by bittiger-java** [comment]
serialization and deserialization issue. 把json message 放上来看看

**Comment by bihjuchiu** [comment]
json message 是 week3-4-for-students/running-location-updater/src/main/resources/public／index.html 自动产生的：
```
{
  "runningId": "4c3476fb-c60e-4970-8c3d-cb788c49f766",
  "point": {
    "latitude": 38.94286343501579,
    "longitude": -76.99099467966852
  },
  "runnerStatus": "NORMAL",
  "speed": 13.8,
  "heading": 236,
}
```

**Comment by bittiger-java** [comment]
前端怎么连接websocket的？有github连接吗？我看一下

**Comment by bihjuchiu** [comment]
https://github.com/bihjuchiu/food-ordering-system/tree/master/order-complete-updater/src/main/resources/public

这个project是

**Comment by bihjuchiu** [comment]
https://github.com/bihjuchiu/food-ordering-system/tree/master/order-complete-updater/src/main/resources/public

这个project的web socket UI 部分 基本上是一样的。。。

**Comment by bihjuchiu** [comment]
Closed the issue by mistake, reopen...

**Comment by hackjutsu** [comment]
@bittiger-java 加油！靠你了！

**Comment by bittiger-java** [comment]
@hackjutsu 😸  @bihjuchiu  https://github.com/bihjuchiu/food-ordering-system/blob/master/order-complete-updater/src/main/resources/public/index.html#L99  please change the queueName to '/topic/orders'

**Comment by bihjuchiu** [comment]
Work了！哇，太厉害了！
谢谢！
